project:
  type: book

book:
  title: "Viswa Kumar | Book Notes for AI Engineering by Chip Huyen"
  author: "Viswa Kumar"
  date: "2025-02-14"
  navbar: 
    right:
      - href: https://github.com/kspviswa/bn-ai-engg
        icon: github
      - href: https://viswakumar.com
        icon: house-door
        text: Home

  chapters:
    - index.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd
    - chapter5.qmd
    - chapter6.qmd
    - chapter7.qmd
    - chapter8.qmd
    - chapter9.qmd
    - chapter10.qmd
    - summary.qmd
    - references.qmd
  page-footer: "Book notes for AI Enggineering by Chip Huyen" 

bibliography: references.bibtex
csl: apa6.csl

format:
  html:
    df-print: paged
    smooth-scroll: true
    #fontsize: 1em
    #mainfont: avenir
    theme: 
      light: [sketchy, css/light.scss]
      #dark: [sketchy, css/dark.scss]
    css: css/styles.css



